name: notes
description: Notes Management .

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_facebook_login: ^3.0.0
  cupertino_icons: ^0.1.3
  provider: ^4.3.1
  shared_preferences: ^0.5.12+4
  font_awesome_flutter: ^8.8.1
  animated_widgets: ^1.0.6
  url_launcher: ^5.5.0
  path_provider: ^1.6.18
  pie_chart: ^4.0.1
  flutter_speed_dial: ^1.2.5
  fluttertoast: ^4.0.1
  flutter_local_notifications: ^1.4.4+1
  rxdart: ^0.25.0
  splashscreen: ^1.3.5
  intl: ^0.16.1
  http: ^0.12.2
  flutter_svg: ^0.19.1
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  google_sign_in: ^4.5.6
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - lib/lang/en.json
    - lib/lang/vi.json
    - lib/lang/fr.json
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf
